FROM python:3.8-slim

WORKDIR /app
RUN echo '#!/bin/sh' > entrypoint.sh && \
    echo 'pytest' >> entrypoint.sh && \
    echo 'pytest --browser firefox' >> entrypoint.sh && \
    echo 'pytest --browser chromium' >> entrypoint.sh && \
    echo 'if [ $? -eq 0 ]; then exit 0; else exit 1; fi' >> entrypoint.sh && \
    chmod +x entrypoint.sh
COPY . ./app

RUN pip install --upgrade pip
RUN pip install pytest pytest-playwright
RUN playwright install
RUN playwright install-deps

CMD ["./entrypoint.sh"]
